In [1]:
import numpy as np

In [3]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
a=np.array([1,2,3])
print(a.ndim)

1


In [11]:
a=np.array(23)
print(a.ndim)

0


In [19]:
a=np.array([[1,2,3],[1,23,3]])
print(a.ndim)

2


In [21]:
a=np.array([[1,2,3],[1,2,3]])
print(a.ndim)

2


In [27]:
a=np.array([[[1,24,4],[1,23,22]],[[2,3,5],[23,53,23]]])
print(a.ndim)

3


In [45]:
a=np.array([[[1,24,4],[10,29,22]],[[2,3,5],[83,53,23]]])
a[1][0][2]

5

In [41]:
a = np.array([[1,8],[5,9]])
print(a[1,1])

9


In [47]:
a=np.array([[[1,24,4],[10,29,22]],[[2,3,5],[83,53,23]]])
print(a[1][1][1])

53


In [49]:
a=np.array([[[4,6,2],[2,3,4]],[[3,4,2],[2,4,2]]])
print(a.ndim)

3


In [51]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

print(a[1:5])

[2 3 4 5]


In [53]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
print(a[0:6])

[1 2 3 4 5 6]


In [55]:
b = np.array([1, 2, 3, 4, 5, 6, 7])

print(b[4:])

[5 6 7]


In [57]:
b = np.array([1, 2, 3, 4, 5, 6, 7])
print(b[3:])

[4 5 6 7]


In [59]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [61]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-4:-2])

[4 5]


In [63]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:-1:2])

[1 3 5]


In [71]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:-2:6])

[1]


In [73]:
d = np.array([[[1, 2, 3, 4, 5],[6,7,8,9,10]],[[11, 12, 13, 14, 15],[16,17,18,19,20]]])
d[1,0,1]

12